lane :test do |options|
  scheme_to_test = "CoinTossingUITests"

  scan_options = {
    scheme: scheme_to_test,
    device: 'iPhone 6',
    output_directory: 'artifacts/tests',
    custom_report_file_name: 'report.xml'
  }
  begin
    retry_count ||= 0
    scan(scan_options)
  rescue => e
    UI.important("failure noted: #{e}")
    report_filepath = File.absolute_path('../artifacts/tests/report.xml')
    unless File.exist?(report_filepath)
      rai